### ISSUE TITLE
[Feature Request] Use shadow window instead of grey out

### ISSUE THREAD

**Issue by kevinhwang91** [mizlan/iswap.nvim#3]
I think the visual effect of a window with `blend`  is better than grey out. I am happy to do a PR for this feature.

**Comment by mizlan** [comment]
This sounds interesting. What would be the dimensions of the window? Would this darken the arguments as well?

**Comment by kevinhwang91** [comment]
https://github.com/sunjon/Shade.nvim like this. I don't like the grey out which hurt my eyes.

**Comment by mizlan** [comment]
I don't want to replace the existing grey-out though, maybe add another option for this. If we are using one floating window, this would imply that the letters and selections become darker as well right? I'm not sure how much I like that.

**Comment by mizlan** [comment]
Could you please make a PR for this so I can see how it looks firsthand?

**Comment by kevinhwang91** [comment]
OK, I will give it a try.

**Comment by kevinhwang91** [comment]
No idea how to anti the blended highlight for the ranges.  I gave up this feature......

**Comment by mizlan** [comment]
Yeah, as far as I'm aware that's not possible with a sane number of windows.
