### ISSUE TITLE
[Feature Request] Add highlight like vim.highlight.on_yank

### ISSUE THREAD

**Issue by kevinhwang91** [mizlan/iswap.nvim#30]
If  `autoswap = true` and the item size of the list is 2, I hardly know whether the items have been swapped.

I want to highlight the swapped items like `vim.highlight.on_yank`. Maybe `IncSearch` and `Search` group for the swapped items are not bad:)

**Comment by mizlan** [comment]
Would this require hardcoding a timer? Is there a utility library that can do the brunt work for me? If not maybe I can write a separate utility and use it here. I would like to learn the schedule system so I will try doing this.

**Comment by kevinhwang91** [comment]
I think use `vim.highlight.on_yank` could implement this feature, no need to add an extra lib.

**Comment by mizlan** [comment]
So would I yank it programmatically to some write-only, unused register?

**Comment by kevinhwang91** [comment]
Oh, I forget `on_yank` will pollute the register, maybe you can reference its implementation:

https://github.com/neovim/neovim/blob/dd8a4e2c22ea8018ce3af989134b1e9c4607ce37/runtime/lua/vim/highlight.lua#L58-L95

**Comment by mizlan** [comment]
I think maybe what I want is these lines:

https://github.com/neovim/neovim/blob/dd8a4e2c22ea8018ce3af989134b1e9c4607ce37/runtime/lua/vim/highlight.lua#L85-L95

**Comment by mizlan** [comment]
@kevinhwang91 it currently seems a bit difficult to get the position of the text after the swap, in cases where the selections can be jagged and extend multiple lines and start/end on arbitrary columns. I think it is possible to math it out... but seems like a lot of debugging ahead

**Comment by kevinhwang91** [comment]
The parent node is immutable, and iswap has been known which children are swapped. Couldn't recapture to get the ranges?

**Comment by mizlan** [comment]
How do you recapture? And if you re-parse the tree, how do you guarantee to get the same nodes again?

**Comment by mizlan** [comment]
It seems ts_utils itself uses some arithmetic to determine where the second one starts (to support the option of jumping to second node):

https://github.com/nvim-treesitter/nvim-treesitter/blob/a5709e685bad789e84e36cb7c95d3b7d60f744d8/lua/nvim-treesitter/ts_utils.lua#L378-L404

**Comment by mizlan** [comment]
I think I did the math correctly :)

**Comment by kevinhwang91** [comment]
Thanks, work as expected.
