### ISSUE TITLE
Support for R 

### ISSUE THREAD

**Issue by sebffischer** [mizlan/iswap.nvim#36]
I would like to use your plugin with R, but when calling :ISwapWith it tells me "Cannot query this filetype". 
Is it possible to extend this to R?

**Comment by mizlan** [comment]
Yes. Could you provide an example R file for which I can do some experimentation? Once I get the file it should take no more than an hour to get it working. Also, sorry for not getting back to you earlier.

**Comment by sebffischer** [comment]
Thank you for you response! Just create a `test.R` file with code:

```r
f = function(a, b = 2) {
  s = a + b
  return(s)
}
```

Note that there is no required ordering of arguments with / without defaults like in python, so the following is also valid: 

```r
f = function(b = 2, a) {
  s = a + b
  return(s)
}
```

**Comment by sebffischer** [comment]
Maybe something to pay attention to would be 

```r
f = function(a = 1, b = a == 1) {
  s = a + b
  return(s)
}

f = function(a = 1, b = sum(a, 1)) {
  s = a + b
  return(s)
}
```

**Comment by mizlan** [comment]
Hi, thanks for the response! Would you be able to include more examples such as function calls, list(/set/dict) literals as well? Every one of these would make the plugin more useful!

**Comment by sebffischer** [comment]
In R essentially everything is a function call, including the construction of lists and vectors (there is currently no dict) 
```r
# Lists in R (are named)
l = list(3, a = 2, 5) 
l[[1]]
l[["a"]]
l[[3]]

# Vectors in R 
vec = c(1, 2, 3) #unnamed
vec = c(a = 1, b = 2, c = 3) #named

# R has the special ... argument (for a variable number of arguments) 
message_sum = function(message = "hallo", ...) {
  print(message)
  return(sum(...))
}
```

Also there are special infix operators such as the primitive `+`, or the above used `[[` that can be called in infix or prefix notation 
```r
`+`(1, 2)

1 + 2

l = list(a = 1, b = 2)
`[[`(l, "b")
l[["b"]]
```

Here are conditionals: 

```r
x = 1
if (x > 1) {
  print("greater than 1")
} else if (x == 1) {
  print("equal to 1")
} else {
  print("smaller than 1")
}
```

**Comment by mizlan** [comment]
Added in https://github.com/mizlan/iswap.nvim/commit/5aa6299bfca77a11dadc8997fc762ed7aaaeda5e, should work now!

**Comment by sebffischer** [comment]
thanks a lot!
