### ISSUE TITLE
Greying out doesn't work well

### ISSUE THREAD

**Issue by rockyzhang24** [mizlan/iswap.nvim#42]
The "grey out the rest of the text" feature doesn't work. I didn't change any default configs and I have already tested several color schemes. 

Before running `:ISwap`
<img width="382" alt="image" src="https://user-images.githubusercontent.com/11582667/151240192-70e1f985-8e17-4502-b7b2-0884c64db25e.png">

After running `:ISwap`
<img width="382" alt="image" src="https://user-images.githubusercontent.com/11582667/151240360-06b2a5e4-7654-4569-974c-f4202412f9e4.png">

Only the variable `x` is greyed. 

Thank you very much.

**Comment by mizlan** [comment]
Yup, this is an issue with newly-implemented highlight priorities. #41 should fix it when it gets merged. Hopefully, you can do without the greying out feature for the time being, and thank you for reporting this issue!

**Comment by rockyzhang24** [comment]
Sure. This plugin is great and definitely I will keep using it. Thank you for fixing this.
