### ISSUE TITLE
Extra comma for lua nested table

### ISSUE THREAD

**Issue by rockyzhang24** [mizlan/iswap.nvim#43]
Look at this piece of lua code
```lua
t = {
  { "abc"	-- (0)
  },	-- (1)
  { "def" 
  },	-- (2)
}
```

(1) and (2) have `},` on a separate line. 

Then position cursor at line (0), execute `:ISwap`, 
<img width="129" alt="image" src="https://user-images.githubusercontent.com/11582667/151607913-a70e77c4-badc-43a6-a702-4d406c6eea7a.png">

Then we swap them,
<img width="268" alt="image" src="https://user-images.githubusercontent.com/11582667/151607980-4f6c37e0-7c24-4b67-89be-26a1242d0149.png">

See, extra commas are put there. 

Thanks you.

**Comment by mizlan** [comment]
I wish I could help but unfortunately I am running into errors when trying to use my own plugin on Lua files 😅 Did you happen to run into anything similar?

**Comment by rockyzhang24** [comment]
I usually use this plugin to swap arguments/parameters in a function. Two days ago, out of curiosity, I wanted to try whether I could swap entries in a table in lua code, and unfortunately it failed.

**Comment by mizlan** [comment]
It should work in theory. Can I see a minimal config that reproduces this issue?

**Comment by rockyzhang24** [comment]
I didn't change any default configurations. Just install this plugin and then run `:ISwap` in a lua file with the demo code above.

**Comment by mizlan** [comment]
This has also made me aware of the issue of comments appearing as tree-sitter nodes. I will create a new issue for this. However, I am also experiencing your error and I suspect it may be an upstream bug.

<img width="274" alt="Screen Shot 2022-02-02 at 10 23 51 AM" src="https://user-images.githubusercontent.com/44309097/152214654-cdc16d17-34c5-4466-b213-130f2b518fff.png">

**Comment by mizlan** [comment]
I've located the specific commit that has caused this issue (not from this repository). Will look into it.

**Comment by rockyzhang24** [comment]
Great! Thank you so much for your effort.

**Comment by mizlan** [comment]
@yanzhang0219 please update nvim-treesitter plugin and see if this issue persists!

**Comment by rockyzhang24** [comment]
@mizlan So sorry for the late reply. Just updated `nvim-treesitter` and this issue has been solved, working like a charm now. Thank you very much. I'll close this.
