### ISSUE TITLE
Raise an error bad argument #1 to concat in ts_utils.lua

### ISSUE THREAD

**Issue by rockyzhang24** [mizlan/iswap.nvim#46]
See the screenshot below please

<img width="1721" alt="image" src="https://user-images.githubusercontent.com/11582667/163886817-e03a1d24-5662-475b-8a2d-593f2359245e.png">

Nvim version I am using: the latest nightly

I think this issue is caused by this commit in nvim-treesitter https://github.com/nvim-treesitter/nvim-treesitter/commit/c3848e713a8272e524a7eabe9eb0897cf2d6932e

Thank you.

**Comment by JoseConseco** [comment]
there is some thread about fix swap nodes: https://github.com/nvim-treesitter/nvim-treesitter/pull/2838

**Comment by rockyzhang24** [comment]
@JoseConseco Wow nice. Thank you. Hope this issue can be fixed after the upstream fixing merged.

**Comment by rockyzhang24** [comment]
Confirmed that this issue was solved after this commit (https://github.com/nvim-treesitter/nvim-treesitter/pull/2838) was merged. I will close this.
