### ISSUE TITLE
Add GIF that shows keypresses

### ISSUE THREAD

**Issue by mizlan** [mizlan/iswap.nvim#5]
It would be nice if the GIF showed keypresses. I think we'd have to use something other than asciicast for that to work.

**Comment by windwp** [comment]
Hi  why i need to press 2 key to swap . it would be better if we can autoselect the params on cursor.

**Comment by mizlan** [comment]
I have considered automatically picking the param under the cursor as the first one, so another one keypress is needed to finalize the swap. Is this what you mean?

**Comment by mizlan** [comment]
I fix this in #15 , see if `:ISwapWith` is what you want.

**Comment by windwp** [comment]
Thank for your fast response. It is working perfect now
