### ISSUE TITLE
Move cursor after swap

### ISSUE THREAD

**Issue by sassanh** [mizlan/iswap.nvim#56]
Thanks for this great extension!
It would be nice if we could change the cursor position to the new position of the node. So for example when you start with:

_a, b
(_ shows the cursor position)
and swap right, it would result in:

b, _a
instead of

_b, a
For reference [vim-swap](https://github.com/machakann/vim-swap) works like this.

**Comment by mizlan** [comment]
Oh yeah, this is relatively trivial with ts_utils, let me push in just a second :) It will be a new option, defaulting to false.

**Comment by mizlan** [comment]
Also, this will/should only work on the `ISwap*With*` commands

**Comment by mizlan** [comment]
Please try and let me know if it works @sassanh!

**Comment by sassanh** [comment]
Yes, it's working. Thanks!
