### ISSUE TITLE
Feature Request: commands to swap with prev/next sibling

### ISSUE THREAD

**Issue by nghialm269** [mizlan/iswap.nvim#59]
Hi, I'm using `nvim-treesitter-textobjects` which allows to define mappings to swap with prev/next parameters. But it doesn't allow to swap in arbitrary list like `iswap` does.

It would be nice if `iswap` could support this feature.

**Comment by mizlan** [comment]
Ah, I guess I am missing `ISwapWithLeft` and `ISwapWithRight`. (It is interesting nvim-treesitter-textobjects only works with parameters) Will keep this on my todo list.

**Comment by mizlan** [comment]
Should be closed in #60 . Let me know if it works!
