### ISSUE TITLE
Add the ability to swap current with next / previous item

### ISSUE THREAD

**Issue by Shatur** [mizlan/iswap.nvim#6]
Hi! thanks for the awesome plugin.
Could you add the ability to swap current item with next / previous without showing keystrokes? This is how it works in [vim-swap](https://github.com/machakann/vim-swap).

**Comment by mizlan** [comment]
This is already implemented in nvim-treesitter-textobjects.

**Comment by mizlan** [comment]
I'm not sure if nvim-treesitter-textobjects allows you to swap things like list elements etc. At any rate, that would be more suitable for a feature request for that particular plugin. Thanks for checking out this plugin though!
