### ISSUE TITLE
Move cursor: stick to where it was?

### ISSUE THREAD

**Issue by kiyoon** [mizlan/iswap.nvim#64]
When using `move_cursor` option with `:ISwap*With*`, it should be preferred to stick to the original cursor location of the node instead of going to the beginning.  
It should be possible to remember to the relative location of the cursor of the node and apply that later on.

**Comment by mizlan** [comment]
Sure this sounds doable. It should be kept in mind that nodes can span multiple lines. I think the approach would be to calculate a (dLine, dCol) offset and apply that?

**Comment by kiyoon** [comment]
Thanks for the reply. I think if a node gets attached to another line, the first line may have a different indent from other lines. I'm not too sure if treesitter will force to keep the shape or not. You may have to keep the relative column position starting from the first character excluding the indent?

**Comment by kiyoon** [comment]
https://github.com/Wansmer/sibling-swap.nvim/blob/71eb9daa5233cd576ce8119bc2dbfa67d4d35462/lua/sibling-swap/utils.lua#L126-L145 

This implementation may be relevant. The plugin seems to do a very similar thing: swapping sibling nodes.

**Comment by mizlan** [comment]
not sure what the problem with indentation is

**Comment by mizlan** [comment]
treesitter node range is `(l_1, c_1), (l_2, c_2)` so with cursor being `(l_c, c_c)` i will try just taking:

`(dl, dc) = (l_c - l_1, c_c - c_1)`

and after the swap with the node's new position at `(l_1', c_1'), (l_2', c_2')`, i will set cursor to `(l_1' + dl, c_1' + dc)`

I think that should work...?

**Comment by kiyoon** [comment]
Yes, it does sound like it should work. Thank you!

**Comment by mizlan** [comment]
Do you think you would be able to quickly try my branch (in the open PR)? I tested it quickly on my end and it seems to work. I am also choosing to add this as a default setting (no option to disable)

**Comment by mizlan** [comment]
we only live once, i'll merge and see...

> it's easier to ask for forgiveness than permission
> \- an old proverb

**Comment by kiyoon** [comment]
Wonderful, thanks! Does it only work with ISwapWith* and not with ISwapNodeWith*?

**Comment by mizlan** [comment]
oops

**Comment by mizlan** [comment]
On second look it seems like it does work correctly?

**Comment by kiyoon** [comment]
> On second look it seems like it does work correctly?

In a python code
```python
print(1)
```
And the cursor is on `t`, it moves to a wrong location

**Comment by mizlan** [comment]
How are you using the plugin? Can you show a quick screen recording?

**Comment by kiyoon** [comment]
[Screencast from 06-01-23 15:59:31.webm](https://user-images.githubusercontent.com/12980409/211049703-79ed7661-ca40-448e-9b24-f4c9449642a3.webm)

I don't know what else to show you.

```lua
require("iswap").setup({
	move_cursor = true,
})

vim.cmd[[
nmap ,s <Cmd>ISwap<CR>
nmap ,S <Cmd>ISwapNode<CR>
nmap ,,s <Cmd>ISwapWith<CR>
nmap ,,S <Cmd>ISwapNodeWith<CR>
nmap <space>. <Cmd>ISwapWithRight<CR>
nmap <space>, <Cmd>ISwapWithLeft<CR>
nmap <space><space>. <Cmd>ISwapNodeWithRight<CR>
nmap <space><space>, <Cmd>ISwapNodeWithLeft<CR>
]]
```

**Comment by mizlan** [comment]
oops let me figure this out, sorry

**Comment by mizlan** [comment]
@kiyoon can you please confirm it works now?

**Comment by mizlan** [comment]
It was a bug in "upstream"... or rather code I had pasted

**Comment by kiyoon** [comment]
It does work well now! Thank you so much!!
