### ISSUE TITLE
Feature Request: Sort alphabetically/numerically

### ISSUE THREAD

**Issue by ethanholz** [mizlan/iswap.nvim#7]
Would be cool to see a feature where you could sort the items rather than doing it manually.

**Comment by mizlan** [comment]
That would indeed be cool. Would that involve re-arranging every element within the node, or do you think it would be better if the user interactively selects a (start, end) range in which everything between those two nodes is sorted?

**Comment by ethanholz** [comment]
I think both might be interesting. The code would be similar judging by what I've seen in the code so far.

**Comment by mizlan** [comment]
I can't think of a satisfying way to sort them. I've considered:
- piping to external program (like Unix utility)
- delegate to Lua or Vimscript function
- lexicographical ordering

It would be helpful if you had an original use in mind, off of which I could base this feature. :)

**Comment by ethanholz** [comment]
I do not have an original use in mind yet. My thought was to tap into your are swapping the values given from treesitter but then use the builtin Lua sort to just sort the table and spit back out the sorted table to the user. I may be able to tackle this issue later this week/month and submit a PR for this functionality.

**Comment by mizlan** [comment]
I don't think this is in the domain of this plugin.
