### ISSUE TITLE
Error: Column value outside range

### ISSUE THREAD

**Issue by tummetott** [mizlan/iswap.nvim#70]
The following option is set: `move_cursor = true`

Now I'm editing a `lua` file with the following content (cursor is at the `|` position):
```lua
cmd = {
    'ISwap',
    'ISwapWith',
    'ISwapNode',
|   'ISwapNodeWith',
    'ISwapWithLeft',
    'ISwapWithRight',
    'ISwapNodeWithLeft',
    'ISwapNodeWithRight',
}
```

Then I run the ex command `:ISwapNodeWithLeft` and I get the following error:

```
E5108: Error executing lua /Users/tummetott/Projects/iswap.nvim/lua/iswap/internal.lua:160: Column value outside range
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        /Users/tummetott/Projects/iswap.nvim/lua/iswap/internal.lua:160: in function 'swap_nodes_and_return_new_ranges'
        /Users/tummetott/Projects/iswap.nvim/lua/iswap.lua:155: in function 'iswap_node_with'
        [string ":lua"]:1: in main chunk
```
It seems like the `nvim_win_set_cursor()` errors because the range is not sanity checked. Running it silent could also solve the error. What do you think?

x Tummetott

**Comment by tummetott** [comment]
When I run the command `:ISwapWithLeft` with the same file and cursorposition I get another error:

```
not on a node!
E5108: Error executing lua /Users/tummetott/Projects/iswap.nvim/lua/iswap.lua:306: attempt to perform arithmetic on a nil value
stack traceback:
        /Users/tummetott/Projects/iswap.nvim/lua/iswap.lua:306: in function 'iswap_with'
        [string ":lua"]:1: in main chunk
```

**Comment by mizlan** [comment]
Ooh okay, thank you for finding and reporting this. I will try to figure it
out asap

**Comment by mizlan** [comment]
For the first one I believe I have fixed it. The second one is expected behavior but I forgot to add an early return.

**Comment by tummetott** [comment]
> The second one is expected behavior but I forgot to add an early return

I still get the same error for the second one.

First one is fixed 🥳

**Comment by tummetott** [comment]
I noticed another bug:
When extending the file with a comment like this (cursor is at `█`):
```lua
cmd = {
    'ISwap',
    'ISwapWith',
    'ISwapNode',
    -- comment
    'ISwapNo█eWith',
    'ISwapWithLeft',
    'ISwapWithRight',
    'ISwapNodeWithLeft',
    'ISwapNodeWithRight',
}
```

and then you execute `:ISwapWithLeft`, the file ends up like this:

```lua
cmd = {
    'ISwap',
    'ISwapWith',
    'ISwapNode',
    'ISwapNo█eWith'
    -- comment,
    'ISwapWithLeft',
    'ISwapWithRight',
    'ISwapNodeWithLeft',
    'ISwapNodeWithRight',
}
```

Note that the comma after the swaped node is moved to the comment (or maybe the comma is not moved with the node). Is this intended?

**Comment by tummetott** [comment]
And the last error I experienced is: When I run any of the `:ISwap...` commands inside a filetype where no treesitter parser is installed, it errors with a very long cryptic messages.

**Comment by mizlan** [comment]
Shoot thanks did not see this before merging

**Comment by tummetott** [comment]
Shall i open another issue with the remaining errors or do you till track them?
thanks
