### ISSUE TITLE
Typed parameters in PHP only swap when cursor is on type name

### ISSUE THREAD

**Issue by adaviloper** [mizlan/iswap.nvim#78]
```
    public function getAnswer(string $question, int $test)
    {
        return match ($question) {
            'starships' => $this->getStarships()
        };
    }
```
If the cursor is on a character in `string` or `int` on either parameter, the entire parameter and type get swapped as expected. However, if the cursor is on the variable name (not the `$`), then nothing happens.
Curiously, when the cursor is on the `$` in `int $test` and I swap right, nothing happens (makes sense), but if I swap left, then the it changes places with `int`.

**Comment by adaviloper** [comment]
This seems to also be an issue in C and is likely related to parameters with more than one text object.

**Comment by mizlan** [comment]
What specific command are you using? I might add a bit better documentation, but basically

`ISwapWithLeft` and `ISwapWithRight` are "intelligent" with regards to parameters (I believe it should work correctly here), while

`ISwapNodeWithLeft` and `ISwapNodeWithRight` are more flexible and can swap many types of nodes in many different situations, but this means it will detect the type and variable name as adjacent and swap those instead.

**Comment by adaviloper** [comment]
Ah, it seems that's exactly what's going on. Sorry about that; it was just my own misunderstanding of the documentation. 

Thanks for the explanation! This plugin is awesome!
